# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: $(Build.ArtifactStagingDirectory)/dist.zip
    replaceExistingArchive: true

- task: CopyFiles@2
  displayName: 'Copy files'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**/*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
    ArtifactName: 'drop'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'FreeLunchFantasySubscription(e2d91e5f-7659-43aa-bffc-22aed71fcb48)'
    appType: 'webAppLinux'
    WebAppName: 'freelunchfantasy'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/drop/dist.zip'
    RuntimeStack: 'NODE|18-lts'
    StartupCommand: 'pm2 serve /home/site/wwwroot/fl-app'